Landing page stats
Synthetify/synthetify-landing pull request #36
Opened 2021-09-22 10:15 UTC by Kimi82

Added dynamically loaded data from API to stats into landing page

2021-09-22 10:26 UTC, awojciak commented on src/components/HomePageSections/Statistics/Statistics.tsx
> +interface IProps {
why are you duplicating this interface?

2021-09-22 10:28 UTC, awojciak commented on src/containers/HomePageStatisticsContainer/HomePageStatisticsContainer.tsx
> +          const helperArray: number[] = [value.at(-1).volume, value.at(-1).collateral, value.at(-1).mint]
maybe move this immediately to setData instead of declaring new variable?

2021-09-22 10:29 UTC, awojciak requested changes

2021-09-22 10:29 UTC, awojciak commented on src/containers/HomePageStatisticsContainer/HomePageStatisticsContainer.tsx
> +      await fetch('https://api.synthetify.io/stats/devnet')
mainnet

2021-09-23 08:25 UTC, PawelKrawczyk96 commented
I think container with component it might be bigger, maybe use % instead of px in width.

![Screenshot from 2021-09-23 10-22-02](https://user-images.githubusercontent.com/37472310/134475679-6767bc1c-678e-4ccf-861e-1992b2714689.png)

2021-09-24 05:52 UTC, awojciak requested changes
![obraz](https://user-images.githubusercontent.com/48929607/134624992-220f7003-88bd-47ef-a874-610379ce863d.png)

2021-09-24 06:08 UTC, awojciak requested changes

2021-09-24 06:08 UTC, awojciak commented on src/containers/HomePageStatisticsContainer/HomePageStatisticsContainer.tsx
> +          setData([helperVariable.at(-1).volume, helperVariable.at(-1).collateral, helperVariable.at(-1).synthetic])
i forgot about one thing: in stats component it is written that these are stats for last month, but here you're only using stats for last day, so fix it

2021-09-24 09:48 UTC, awojciak approved these changes

2021-09-24 09:49 UTC, merged