add language Polski to landing
Synthetify/synthetify-landing pull request #50
Opened 2021-10-07 14:02 UTC by Pawel-Szydlo

2021-10-07 14:16 UTC, K-Pomian commented on src/static/translations/polski.ts
> +    'Wykorzystaj swoje ulubione aktywa jako zabezpieczenia lub stwórz ich syntetyczne wersje.',
Zabezpieczenie

2021-10-07 14:20 UTC, K-Pomian commented on src/static/translations/polski.ts
> +  'home.statistics.liquidation': 'Liquidation',
'Volume' -> 'Wolumen'
'Collaterals' -> 'Zabezpieczenia'
'Synthetics' -> 'Syntetyki'
'Liquidation' -> 'Likwidacja'

2021-10-07 14:26 UTC, K-Pomian commented on src/static/translations/polski.ts
> +    'Czy są jakieś korzyści ze stakowania?',
'stakowania' -> 'obstawiania'

2021-10-07 14:28 UTC, K-Pomian commented on src/static/translations/polski.ts
> +    'Jak mogę sprawdzić, czy transakcja została zrealizowana?',
Without comma after "sprawdzic"

2021-10-07 14:44 UTC, K-Pomian requested changes
Some translations to be changed

2021-10-08 07:57 UTC, awojciak commented on src/providers/LanguageProvider/LanguageProvider.tsx
> +      ? (localStorage.getItem('language') as Language)
you can move this condition up to use one ternary operator instead of two

2021-10-08 08:38 UTC, NorbertBodziony requested changes

2021-10-08 08:38 UTC, NorbertBodziony commented on src/static/translations/english.ts
> +  'header.githublDescription': 'Find us on Github',
????

2021-10-11 06:02 UTC, merged